apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-vol
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.148.75
    path: "/"
  mountOptions:
    - nfsvers=4.2
