---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nfs-busybox-backend.yaml
- nfs-frontend-service.yaml
- nfs-nginx-frontend.yaml
- nfs-pvc.yaml
- nfs-pv.yaml 
- nfs-route.yaml