apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.30.233.43
    path: "/"
  mountOptions:
    - nfsvers=4.2
